### ISSUE TITLE
Contact Page needs to be completed

### ISSUE THREAD

**Issue by kernelpanic77** [zense/zense-website-new#11]
Contact page needs to be completed according to the figma design. 

https://www.figma.com/file/02OgVi0VsQixVsuxQ5RGww/ZenseWebsite?node-id=0%3A1

**Comment by sriramun** [comment]
Can I work on this?

**Comment by GSri30** [comment]
> Can I work on this?

Sure. Go ahead. Please keep updating your progress.

**Comment by sriramun** [comment]
Pull Request: #14

**Comment by GSri30** [comment]
> Pull Request: #14

@kernelpanic77
