### ISSUE TITLE
Change Pics and Content of About Page

### ISSUE THREAD

**Issue by kernelpanic77** [zense/zense-website-new#12]
Pics available in figma design. 
https://www.figma.com/file/02OgVi0VsQixVsuxQ5RGww/ZenseWebsite?node-id=0%3A1

**Comment by sriramun** [comment]
Can I work on this?

**Comment by kernelpanic77** [comment]
Sure @sriramun 
@GSri30 has assigned you to the issue already.

**Comment by sriramun** [comment]
PR: #21

**Comment by vijay-jaisankar** [comment]
Relevant PRs: #21 and #24

**Comment by vijay-jaisankar** [comment]
The relevant PRs have been merged.

Hence, I'm closing this issue :)
