### ISSUE TITLE
Improve mobile compatibility of home page

### ISSUE THREAD

**Issue by sriramun** [zense/zense-website-new#15]
The tagline isn't completely visible currently (on screens with smaller dimensions).

![image](https://user-images.githubusercontent.com/72118247/139303366-0ae4c724-5811-4447-8f1b-71bce642b910.png)

**Comment by kernelpanic77** [comment]
Okay yeah! So we just noticed this today, you will need media-queries to solve this issue. 
https://www.w3schools.com/css/css3_mediaqueries.asp

**Comment by vijay-jaisankar** [comment]
@kernelpanic77 The `Think, Develop, Deploy` part has been removed with the PR #19. Does this issue still persist? If no, we can close this issue.
